image: python:3.7.3

test: &test
  step:
    caches:
      - pip
    script:
      - pip install -r dev-requirements.txt
      - tox

push: &push
  step:
    script:
      - pipe: atlassian/pypi-publish:0.2.11
        variables:
          PYPI_USERNAME: '$PYPI_USERNAME'
          PYPI_PASSWORD: '$PYPI_PASSWORD'

pipelines:
  default:
    - <<: *test
  branches:
    master:
    - <<: *test
    - <<: *push
